### ISSUE TITLE
Missile

### ISSUE THREAD

**Issue by jordanlrothwell** [jordanlrothwell/missile_command#4]
- [x] missile trajectory
- [x] display missile 
- [x] collision detection

**Comment by jordanlrothwell** [comment]
## To-Do List

### Required
- [ ] Update missile generation so it generates a valid random coord (or use a helper method)
- [ ] Ensure missiles don't travel indefinitely if they don't collide with a city
- [ ] Fix buggy colour issues while missiles are being displayed (city edge outlines change, flashing doesn't behave as intended)

---
